services:
  app:
    build: .
    container_name: NEXT-AUTH_APP_SERVER
    environment:
      - DATABASE_URL=postgresql://postgres:Hameed_2003@db:5432/NEXT-AUTH_APP_DATABASE
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: NEXT-AUTH_APP_DATABASE
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hameed_2003
      POSTGRES_DB: NEXT-AUTH_APP_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
